# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 185884083a8ca7e232ce416d6c790b954a9724f9a658402f217bfde0558842e182771364b30415482eba07362a555b7e9a21d31999792d7c0227fc61d477fd9f

test:
  secret_key_base: a70b7d6e3585c775983677b4a18c50f56f8f3f26fea4df3b2a9653d8e73c531abd693302fc86a2a6c40b411b542cea090b857f12b7231318bf8874311393c4a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
